version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: develop_pass
      MYSQL_DATABASE: users
      MYSQL_USER: production
      MYSQL_PASSWORD: production_password
    ports:
      - "6033:3306"
    volumes:
      - ./production/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  web:
    build:
      context: app
    environment:
      PASSWORD: production_password
      USERNAME: production
      SERVER: mysql
      PORT: 3306
    ports:
      - "5010:5000"
    depends_on:
      - mysql